[package]
name = "denali"
version = "0.1.0"
edition = "2024"
default-run = "denali"

[dependencies]
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
console-subscriber.workspace = true
derive_more.workspace = true
futures.workspace = true
glob.workspace = true
hex.workspace = true
libloading.workspace = true
log.workspace = true
notify.workspace = true
rocksdb.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
